### ISSUE TITLE
This mod sucks, ASS.

### ISSUE THREAD

**Issue by REALHaydenGaming** [FrogB/VsDaveAndBambiArchives#1]
### What is your question?

Holy shit, time to criticize this mod:

- Stolen Code
- Publicizing code of others who DONT want there code to be replicated.
- This, is, so, **LOW EFFORT.**

Like it looks you didnt even try on most of the songs, and that goofy ass **_lyrics_** script shouldn't even be in the songs???????

**Comment by FrogB** [comment]
1. This mod is not meant to be taken seriously, yes it may have contained a minimal amount of unauthorized assets.
2. Parts of the code were already public even before this mod was formed.
3. If you really want to hate on this mod, do NOT ever bring it to this page, as it may receive a bad reputation.
4. As mentioned in Gamebanana, this mod is considered low - mid effort. There is no need for a second reminder.
5. The lyrics script can be useless sometimes, but it is sometimes meant for people who are interested in what characters are saying in the mod.
6. "Didn't even try on"? Do you know how many fucking times I have to playtest every single update before it even gets published? And at the same time my team of playtesters sitting there and not even in the fucking mood to help me out?

To end this, I simply ask that you fuck off.
